### ISSUE TITLE
GUI UX:  unable to read selected context menu item due to row background/foreground color  choice

### ISSUE THREAD

**Issue by newbie321** [samdark/intellij-visual-studio-code-dark-plus#43] opened 2021-05-19 22:00 UTC
### What the issue is?

The context menu appears when the user right-clicks anywhere within the editor.    The background of a selected row is too bright  for the text's color.  Foreground:  white; background: bright pale-blue.    Such color combination results in a visually non-readable menu option, which affects UX (user experience).  

### Screenshots

![image](https://user-images.githubusercontent.com/8405053/118889933-7d954480-b8c3-11eb-9047-e93de3860e09.png)

### How would you fix it?
Proposal:  Change the foreground color from white to black (anything dark)  and keep the same background
OR 
change the background from bright pale blue to something darker (brown, plum, indigo) and keep the same foreground

A nicer alternative to all of this would be:
Provide options in settings so that user can adjust colors to his/her liking... 

Thanks!! 

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.?
| IDE and version  | 
| Operating system |

**Comment by samdark** [comment] 2021-05-20 19:27
That's how it looks in my case:

![image](https://user-images.githubusercontent.com/47294/119037406-9a607380-b9ba-11eb-8c97-8b9eda4417b6.png)

Seems to be OS dependent.

**Comment by samdark** [comment] 2021-08-03 20:38
Closing since I can not reproduce it.

**Closed by samdark** 2021-08-03 20:38 UTC
Labels: bug
